### ISSUE TITLE
Log to AWS S3

### ISSUE THREAD

**Issue by coderbyheart** [PascalPickel/NAT-TestServer#4]
We need to transmit the logs out of the system to be backed up, and analyzed and we will be using AWS S3 for that.

Please make yourself familiar with the Go SDK: https://github.com/aws/aws-sdk-go

Here is an example that uploads a file to S3: https://github.com/aws/aws-sdk-go/tree/29ad100f6b7acd1254f8a3ac6c3d2955488bc4b8#complete-sdk-example

You most likely will be writing one file per log entry, so make sure not to overwrite files.

**Comment by PascalPickel** [comment]
e7f5bf5
